VERSION 0.6
FROM ../common+base

WORKDIR /dependabot-maven

shared:
    FROM scratch

    COPY --dir lib spec maven/
    COPY dependabot-maven.gemspec maven/
    SAVE ARTIFACT maven

deps:
    COPY --dir ../common+shared/common ../common
    COPY Gemfile *.gemspec .
    RUN bundle install --jobs 4 --retry 3

    COPY --dir lib spec .

test:
    FROM +deps

    RUN bundle exec rspec spec

lint:
    FROM +deps

    COPY ../+shared/.rubocop.yml ../
    COPY .rubocop.yml .
    RUN bundle exec rubocop .
