VERSION 0.6
FROM ruby:2.7.1
WORKDIR /dependabot-terraform

ARG TERRAFORM_VERSION=1.2.0
ARG TERRAFORM_AMD64_CHECKSUM=b87de03adbdfdff3c2552c8c8377552d0eecd787154465100cf4e29de4a7be1f
ARG TERRAFORM_ARM64_CHECKSUM=ee80b8635d8fdbaed57beffe281cf87b8b1fd1ddb29c08d20e25a152d9f0f871

ARG HCL2JSON_VERSION=0.3.3
ARG HCL2JSON_CHECKSUM=24068f1e25a34d8f8ca763f34fce11527472891bfa834d1504f665855021d5d4

SETUP:
    COMMAND

    ENV DEPENDABOT_NATIVE_HELPERS_PATH="${DEPENDABOT_NATIVE_HELPERS_PATH:-/opt}"

    COPY +helpers/terraform /usr/local/bin
    COPY +helpers/hcl2json $DEPENDABOT_NATIVE_HELPERS_PATH/terraform/bin/hcl2json

helpers:
    FROM ubuntu:20.04

    ARG TARGETOS
    ARG TARGETARCH

    ARG DEBIAN_FRONTEND="noninteractive"

    RUN apt-get update \
     && apt-get install -y --no-install-recommends \
          build-essential \
          ca-certificates \
          curl \
          zlib1g-dev \
          liblzma-dev \
          unzip \
     && rm -rf /var/lib/apt/lists/*

    RUN curl -o terraform-${TARGETARCH}.tar.gz \
            https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${TARGETARCH}.zip \
     && echo "$TERRAFORM_AMD64_CHECKSUM  terraform-amd64.tar.gz\n$TERRAFORM_ARM64_CHECKSUM  terraform-arm64.tar.gz\n" \
            | sha256sum -c --ignore-missing - \
     && unzip -d terraform terraform-${TARGETARCH}.tar.gz \
     && rm terraform-${TARGETARCH}.tar.gz
    SAVE ARTIFACT terraform

    RUN curl -sSLf "https://github.com/tmccombs/hcl2json/releases/download/v${HCL2JSON_VERSION}/hcl2json_${TARGETOS}_${TARGETARCH}" -o hcl2json \
     && echo "$HCL2JSON_CHECKSUM hcl2json" | sha256sum -c \
     && chmod +x hcl2json
    SAVE ARTIFACT hcl2json

deps:
    COPY --dir ../common+shared/common ../common
    COPY Gemfile *.gemspec .
    RUN bundle install --jobs 4 --retry 3

    COPY --dir lib spec .

test:
    FROM +deps
    DO +SETUP

    DO ../common+CONFIGURE_GIT_USER

    RUN bundle exec rspec spec

lint:
    FROM +deps

    COPY ../+shared/.rubocop.yml ../
    COPY .rubocop.yml .
    RUN bundle exec rubocop .
