VERSION 0.6
FROM ../common+base

WORKDIR /dependabot-pub

ARG DART_VERSION=2.16.2
ARG FLUTTER_VERSION=2.10.3
ARG PUB_REF=1e3c17ea871e6a80c720aa998f37cbd3913bc287

SETUP:
    COMMAND

    ARG TARGETARCH

    ENV DEPENDABOT_NATIVE_HELPERS_PATH="${DEPENDABOT_NATIVE_HELPERS_PATH:-/opt}"

    USER root

    ENV PUB_CACHE=$DEPENDABOT_NATIVE_HELPERS_PATH/dart/pub-cache
    ENV PUB_ENVIRONMENT="dependabot"
    ENV PATH="$DEPENDABOT_NATIVE_HELPERS_PATH/dart/dart-sdk/bin:$PATH"

    # Install Dart
    RUN DART_ARCH=${TARGETARCH} \
     && if [ "$TARGETARCH" = "amd64" ]; then DART_ARCH="x64"; fi \
     && curl --connect-timeout 15 --retry 5 "https://storage.googleapis.com/dart-archive/channels/stable/release/${DART_VERSION}/sdk/dartsdk-linux-${DART_ARCH}-release.zip" \
            > "/tmp/dart-sdk.zip" \
     && mkdir -p "$PUB_CACHE" \
     && unzip "/tmp/dart-sdk.zip" -d $DEPENDABOT_NATIVE_HELPERS_PATH/dart > /dev/null \
     && chmod -R o+rx $DEPENDABOT_NATIVE_HELPERS_PATH/dart/dart-sdk \
     && rm "/tmp/dart-sdk.zip" \
     && dart --version

    # We pull the dependency_services from the dart-lang/pub repo as it is not
    # exposed from the Dart SDK (yet...).
    GIT CLONE --branch $PUB_REF https://github.com/dart-lang/pub.git $DEPENDABOT_NATIVE_HELPERS_PATH/dart/pub
    RUN dart pub global activate --source path $DEPENDABOT_NATIVE_HELPERS_PATH/dart/pub \
     && chmod -R o+r $DEPENDABOT_NATIVE_HELPERS_PATH/dart/pub

    # Install Flutter
    RUN curl --connect-timeout 15 --retry 5 "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz" \
            > "/tmp/flutter.xz" \
     && tar xf "/tmp/flutter.xz" -C $DEPENDABOT_NATIVE_HELPERS_PATH/dart \
     && rm "/tmp/flutter.xz" \
     && chmod -R o+rx $DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter \
     # To reduce space usage we delete all of the flutter sdk except the few
     # things needed for pub resolutions:
     # * The version file
     # * The flutter sdk packages.
     && find $DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/version' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/packages/*' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/packages' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/bin/cache/pkg/*' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/bin/cache/pkg' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/bin/cache' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter/bin' \
       ! -path '$DEPENDABOT_NATIVE_HELPERS_PATH/dart/flutter' \
       -delete

deps:
    COPY --dir ../common+shared/common ../common
    COPY Gemfile *.gemspec .
    RUN bundle install --jobs 4 --retry 3

    COPY --dir lib spec .

test:
    FROM +deps
    DO +SETUP

    DO ../common+CONFIGURE_GIT_USER

    RUN bundle exec rspec spec

lint:
    FROM +deps

    COPY ../+shared/.rubocop.yml ../
    COPY .rubocop.yml .
    RUN bundle exec rubocop .
