VERSION 0.6
FROM ../common+base

WORKDIR /dependabot-hex

ARG ELIXIR_VERSION=1.12.3
ARG ELIXIR_CHECKSUM=db092caa32b55195eeb24a17e0ab98bb2fea38d2f638bc42fee45a6dfcd3ba0782618d27e281c545651f93914481866b9d34b6d284c7f763d197e87847fdaef4

SETUP:
    COMMAND

    ENV DEPENDABOT_NATIVE_HELPERS_PATH="${DEPENDABOT_NATIVE_HELPERS_PATH:-/opt}"

    USER root

    ENV PATH="/usr/local/elixir/bin:$PATH"
    ENV MIX_HOME="$DEPENDABOT_NATIVE_HELPERS_PATH/hex/mix"

    RUN apt-get update \
     && apt-get install -y --no-install-recommends \
         erlang \
     && rm -rf /var/lib/apt/lists/* \
     && curl -sSLfO https://github.com/elixir-lang/elixir/releases/download/v${ELIXIR_VERSION}/Precompiled.zip \
     && echo "$ELIXIR_CHECKSUM  Precompiled.zip" | sha512sum -c - \
     && unzip -d /usr/local/elixir -x Precompiled.zip \
     && rm -f Precompiled.zip \
     && mix local.hex --force \
     && mix archive.install hex nerves_bootstrap --force

    DO ../common+CREATE_DEPENDABOT_USER
    COPY --chown=dependabot:dependabot +helpers/hex $DEPENDABOT_NATIVE_HELPERS_PATH/hex

helpers:
    FROM elixir:$ELIXIR_VERSION

    COPY --dir helpers .

    WORKDIR helpers

    RUN mix local.hex --force
    RUN mix deps.get

    SAVE ARTIFACT . hex

deps:
    COPY --dir ../common+shared/common ../common
    COPY Gemfile *.gemspec .
    RUN bundle install --jobs 4 --retry 3

    COPY --dir lib spec .

test:
    FROM +deps
    DO +SETUP

    RUN bundle exec rspec spec

lint:
    FROM +deps

    COPY ../+shared/.rubocop.yml ../
    COPY .rubocop.yml .
    RUN bundle exec rubocop .
