VERSION 0.6
FROM ../common+base
WORKDIR /dependabot-composer

ARG COMPOSER_V1_VERSION=1.10.26
ARG COMPOSER_V2_VERSION=2.3.5

ARG COMPOSER_ALLOW_SUPERUSER=1

SETUP:
    COMMAND

    ENV DEPENDABOT_NATIVE_HELPERS_PATH="${DEPENDABOT_NATIVE_HELPERS_PATH:-/opt}"

    USER root

    ARG DEBIAN_FRONTEND="noninteractive"

    RUN apt-get update \
     && apt-get install -y --no-install-recommends \
            software-properties-common \
     && add-apt-repository ppa:ondrej/php \
     && apt-get update \
     && apt-get install -y --no-install-recommends \
            php7.4 \
            php7.4-apcu \
            php7.4-bcmath \
            php7.4-cli \
            php7.4-common \
            php7.4-curl \
            php7.4-gd \
            php7.4-geoip \
            php7.4-gettext \
            php7.4-gmp \
            php7.4-imagick \
            php7.4-imap \
            php7.4-intl \
            php7.4-json \
            php7.4-ldap \
            php7.4-mbstring \
            php7.4-mcrypt \
            php7.4-memcached \
            php7.4-mongodb \
            php7.4-mysql \
            php7.4-redis \
            php7.4-soap \
            php7.4-sqlite3 \
            php7.4-tidy \
            php7.4-xml \
            php7.4-zip \
            php7.4-zmq \
     && rm -rf /var/lib/apt/lists/*

    DO ../common+CREATE_DEPENDABOT_USER

    COPY --chown=dependabot:dependabot +composer-v1/composer "$DEPENDABOT_NATIVE_HELPERS_PATH/composer/bin/composer1"
    COPY --chown=dependabot:dependabot +composer-v2/composer "$DEPENDABOT_NATIVE_HELPERS_PATH/composer/bin/composer"
    
    ENV PATH="$DEPENDABOT_NATIVE_HELPERS_PATH/composer/bin:$PATH"

    COPY --chown=dependabot:dependabot +composer-v1/helpers "$DEPENDABOT_NATIVE_HELPERS_PATH/composer/v1"
    COPY --chown=dependabot:dependabot +composer-v2/helpers "$DEPENDABOT_NATIVE_HELPERS_PATH/composer/v2"

    USER dependabot

    # Perform a fake `composer update` to warm ~/dependabot/.cache/composer/repo
    # with historic data (we don't care about package files here)
    RUN mkdir /tmp/composer-cache \
     && cd /tmp/composer-cache \
     && echo '{"require":{"psr/log": "^1.1.3"}}' > composer.json \
     && composer update --no-scripts --dry-run \
     && cd /tmp \
     && rm -rf /home/dependabot/.cache/composer/files \
     && rm -rf /tmp/composer-cache
    
    USER root

composer-v1:
    FROM composer:$COMPOSER_V1_VERSION
    SAVE ARTIFACT /usr/bin/composer

    WORKDIR helpers
    COPY helpers/v1 .

    # RUN composer validate --no-check-publish
    RUN composer install --ignore-platform-reqs
    # RUN composer run lint -- --dry-run
    RUN composer run stan

    SAVE ARTIFACT .

composer-v2:
    FROM composer:$COMPOSER_V2_VERSION
    SAVE ARTIFACT /usr/bin/composer

    WORKDIR helpers
    COPY helpers/v2 .

    # RUN composer validate --no-check-publish
    RUN composer install --ignore-platform-reqs
    # RUN composer run lint -- --dry-run
    RUN composer run stan

    SAVE ARTIFACT .

deps:
    # FIXME: 2022-03-17
    # Our helper scripts require php 7.4.
    # The official Ruby container uses a version of Ubuntu that
    # that installs php 7.3 by default.
    # However, the PPA that hosts php 7.4
    # doesn't currently support this version of Ubuntu
    # ("The repository 'http://ppa.launchpad.net/ondrej/php/ubuntu jammy Release' does not have a Release file.")
    # Therefore, we're building up a new base container
    # that installs Ruby and php 7.4 manually.
    FROM ../+deps
    DO ../bundler/+SETUP
    WORKDIR /dependabot-composer
    # TODO: Remove the above code once the official Ruby container can be used.

    COPY --dir ../common+shared/common ../common
    COPY Gemfile *.gemspec .
    RUN bundle install --jobs 4 --retry 3

    COPY --dir lib spec .

test:
    FROM +deps

    DO +SETUP

    RUN bundle exec rspec spec

lint:
    FROM +deps

    COPY ../+shared/.rubocop.yml ../
    COPY .rubocop.yml .
    RUN bundle exec rubocop .
